### ISSUE TITLE
Error en el calculo de la diversidad de sur africa

### ISSUE THREAD

**Issue by JuanHigueraC** [complexluise/Flujos_Diversidad_Comercio_Internacional#2]
El país de sur africa no se encuentra como tal en las transacciones de la base de datos de BACI, es necesario por lo tanto, ajustar el codigo para que no ocurra este error de tomar paises de los cuales no tenemos datos en BACI, para esto se recomienda tomar como lista de paises para iterar, los paises directamente sacandos de los datos de BACI y no los del banco mundial

**Comment by complexluise** [comment]
En el [PR No.4](https://github.com/complexluise/Flujos_Diversidad_Comercio_Internacional/pull/4) se modifico el comportamiento para tomar los paises de BACI.
![image](https://github.com/user-attachments/assets/0ab45b4e-ea84-4530-b972-87b8247fee3f)
